# Positional Encoding from scratch

In [9]:
import numpy as np
import matplotlib.pyplot as plt

Self-attention is a very good tool for comparing vectors with other vectors. However vectors by themselves do not contain position unless we put it in somehow. 

In [10]:
tokens = ["the", "cat", "sat", "down"]

for i, tok in enumerate(tokens):
    print(f"position: {i}, token: {tok}")

position: 0, token: the
position: 1, token: cat
position: 2, token: sat
position: 3, token: down


A sequence has two components, its content and its position. The content tells us what the token is while the position tells us where the token sits. In our case we have:

- The token "the" has the content "the" and the position O
- The token "cat" has the content "cat" and the position 1
- The token "sat" has the content "sat" and the position 2
- The token "down" has the content "down" and the position 3

A model that sees only the content has no chance of automatically knowing the order. 

Now we are going to map our tokens to embeddings (vectors) but without a position yet. 

In [11]:
token_2_vec = {

    "the": np.array([1.0, 0.0, 0.0, 0.0]),
    "cat": np.array([0.0, 1.0, 0.0, 0.0]),
    "sat": np.array([0.0, 0.0, 1.0, 0.0]),
    "down": np.array([0.0, 0.0, 0.0, 1.0]),
}

X = np.stack([token_2_vec[t] for t in tokens])
print(f"X: {X}, shape: {X.shape}")

X: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape: (4, 4)


So now each token is represented as a vector. However each of these vectors now tell us that one vector is corresponding to a meaning. For example [0.0, 1.0, 0.0, 0.0] corresponds to "cat" but it does not tell us whether cat came first or second. We need to encode its position.